import Link from 'next/link'
import {auth} from '@/auth'
import {db} from '@/lib/db'
import {adminTwoFactorOk} from '@/lib/admin-2fa'
export default async function AdminOrders(){
 const s=await auth();if(!s?.user?.id)return <main className="section wrap"><div className="card"><Link className="btn primary" href="/login">Sign in</Link></div></main>;const a=await db.user.findUnique({where:{id:s.user.id}});if(a?.role!=='ADMIN'||!(await adminTwoFactorOk(a.id)))return <main className="section wrap"><div className="card"><Link className="btn primary" href="/admin/2fa">Verify Admin device</Link></div></main>
 const [market,store]=await Promise.all([db.order.findMany({where:{status:{in:['PAID','IN_PROGRESS','DELIVERED','DISPUTED']}},include:{buyer:{select:{username:true}},seller:{select:{username:true}},listing:{select:{title:true}}},orderBy:{createdAt:'desc'},take:80}),db.storeOrder.findMany({where:{status:{in:['PAID','PROCESSING','FLAGGED']}},include:{user:{select:{username:true}},product:{select:{title:true}}},orderBy:{createdAt:'desc'},take:80})])
 return <main className="wrap section"><div className="row" style={{justifyContent:'space-between'}}><div><h1>Orders</h1><p className="muted">Marketplace protection and Official Store processing.</p></div><Link className="btn" href="/admin">Admin home</Link></div><h2 style={{marginTop:24}}>Marketplace</h2><div className="grid">{market.map((o: typeof market[number]) =><div className="card" key={o.id}><strong>{o.listing.title}</strong><div className="small muted">@{o.buyer.username} → @{o.seller.username}</div><div className="small">{o.amount} ETB · {o.status}</div><div className="row" style={{marginTop:10}}><form action={`/api/admin/marketplace-orders/${o.id}`} method="post"><input type="hidden" name="action" value="COMPLETE"/><button className="btn primary">Complete</button></form><form action={`/api/admin/marketplace-orders/${o.id}`} method="post"><input type="hidden" name="action" value="CANCEL"/><button className="btn">Cancel</button></form><form action={`/api/admin/marketplace-orders/${o.id}`} method="post"><input type="hidden" name="action" value="REFUND"/><button className="btn">Refund</button></form></div></div>)}</div><h2 style={{marginTop:24}}>Official Store</h2><div className="grid">{store.map(o=><div className="card" key={o.id}><strong>{o.product.title}</strong><div className="small muted">@{o.user.username} · {o.amount} ETB · {o.status}</div><div className="row" style={{marginTop:10}}><form action={`/api/admin/orders/${o.id}`} method="post"><input type="hidden" name="action" value="PROCESS"/><button className="btn primary">Process</button></form><form action={`/api/admin/orders/${o.id}`} method="post"><input type="hidden" name="action" value="COMPLETE"/><button className="btn">Complete</button></form><form action={`/api/admin/orders/${o.id}`} method="post"><input type="hidden" name="action" value="REFUND"/><button className="btn">Refund</button></form></div></div>)}</div></main>
}
