'use client'
import {useState} from 'react'
const plans=[['PREMIUM',7,99],['PREMIUM',30,299],['PREMIUM',90,799],['PREMIUM',180,1399],['PREMIUM',365,2499],['PREMIUM_PLUS',7,299],['PREMIUM_PLUS',30,499],['PREMIUM_PLUS',90,999],['PREMIUM_PLUS',180,1599],['PREMIUM_PLUS',365,2699]] as const
export function SubscriptionPlans(){
 const [chosen,setChosen]=useState<{id:string,price:number}|null>(null); const [msg,setMsg]=useState('')
 async function create(tier:string,days:number,price:number){setMsg('Creating payment order…');const r=await fetch('/api/subscriptions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tier,days:String(days)})});const x=await r.json();if(!r.ok){setMsg(x.error||'Could not create subscription');return}setChosen({id:x.subscriptionId,price:x.price});setMsg(`Pay ${price} ETB through your configured qBirr receiver, then enter the transaction reference below.`)}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!chosen)return;const fd=new FormData(e.currentTarget);setMsg('Verifying with qBirr…');const r=await fetch('/api/payments/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subscriptionId:chosen.id,provider:fd.get('provider'),ref:fd.get('ref')})});const x=await r.json();setMsg(r.ok&&x.ok?'Payment verified. Subscription activated.':x.error||'Payment not verified')}
 return <><div className="grid">{plans.map(([tier,days,price])=><div className="card" key={`${tier}-${days}`}><div className="check">{tier==='PREMIUM'?'Premium':'Premium+'}</div><h3>{days===7?'7 days':days===30?'1 month':days===90?'3 months':days===180?'6 months':'12 months'}</h3><div className="price">{price} ETB</div><button className="btn primary" onClick={()=>create(tier,days,price)}>Continue</button></div>)}</div>{chosen&&<form onSubmit={verify} className="form" style={{marginTop:20}}><select name="provider" defaultValue="cbe"><option value="cbe">CBE</option><option value="telebirr">Telebirr</option><option value="awash">Awash</option><option value="dashen">Dashen</option><option value="mpesa">M-Pesa</option><option value="abyssinia">Abyssinia</option><option value="ebirr">eBirr</option></select><input name="ref" placeholder="Transaction reference" required/><button className="btn primary">Verify payment</button><span className="small muted">{msg}</span></form>}{!chosen&&msg&&<p className="muted">{msg}</p>}</>
}
